apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: auth-demo-vault-static-ingress
  namespace: auth-demo-vault-static
spec:
  rules:
  - host: auth-demo.hedge.reechar.co
    http:
      paths:
      - backend:
          serviceName: auth-app-vault-static-service
          servicePort: 8080
        path: /vault-static
  tls:
  - hosts:
    - auth-demo.hedge.reechar.co
    secretName: production-crt