apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: auth-demo-kube-secret-ingress
  namespace: auth-demo-kube-secret
spec:
  rules:
  - host: auth-demo.hedge.reechar.co
    http:
      paths:
      - backend:
          serviceName: auth-app-kube-secret-service
          servicePort: 8080
        path: /k8s
  tls:
  - hosts:
    - auth-demo.hedge.reechar.co
    secretName: production-crt