apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: production-crt
  namespace: auth-demo-workload-identity
spec:
  dnsNames:
  - auth-demo.hedge.reechar.co
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: production-crt
