apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-app-kube-secret
  name: auth-app-kube-secret-service
  namespace: auth-demo-kube-secret
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: auth-app-kube-secret
  sessionAffinity: None
  type: NodePort
